# Change these first
owner: dasshept # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: DasShept Website
    url: https://dasshept.de
  - name: JUtils Website
    url: https://jutils.dasshept.de
  - name: JUtils API
    url: https://dasshept.de/api/license/

assignees: # Users to assign downtime issues (optional)
  - dassharkk
  - mcshept

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.dasshept.de
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: DasShept Uptime
  introTitle: "DasShept Service Status"
  introMessage: Here you can find the uptime of our services (ping is from us, we host in germany)
  theme: night
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
